### ISSUE TITLE
トーナメント

### ISSUE THREAD

**Issue by QwerTayu** [NITACwpl/sports-fes-2023#4]

**Comment by hengin-eer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [トーナメントCSS](https://trello.com/c/7UmkGPmS/3-%E3%83%88%E3%83%BC%E3%83%8A%E3%83%A1%E3%83%B3%E3%83%88css)

**Comment by hengin-eer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [トーナメント設計](https://trello.com/c/VyFHLjQp/1-%E3%83%88%E3%83%BC%E3%83%8A%E3%83%A1%E3%83%B3%E3%83%88%E8%A8%AD%E8%A8%88)
